### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by Yukesh0409** [juan-esteban-berger/termpandas#1]
### Missing Dependency: `polars`

**Description:**
While installing `termpandas`, I noticed that the `polars` library, which is required for the tool to work, is not listed in the `requirements.txt` or `install_requires` in `setup.py`. This causes the installation to fail or the tool to not work correctly out of the box.

**Steps to Reproduce:**
1. Create a new virtual environment: `python -m venv env`
2. Install `termpandas`: `pip install termpandas`

**Expected Behavior:**
`termpandas` should install all required dependencies, including `polars`.

**Temporary Workaround:**
Manually install `polars` using `pip install polars`.

**Suggested Fix:**
Add `polars` to the `install_requires` section of `setup.py` or `requirements.txt`.

Thanks for creating this useful tool!

Best regards,
Yukesh A S : )

**Comment by juan-esteban-berger** [comment]
Just added the missing dependency, thanks Yukesh for pointing this out. You can now download the new version using pip.
